### ISSUE TITLE
Policies not working after upgrading to v0.17.5

### ISSUE THREAD

**Issue by staelen** [minio/kes#180] opened 2022-01-05 05:17 UTC
#### Bug description
For version 0.17.5, in `kes.yml`

```
...
policy:
  staging-minio:
    allow:
    - /v1/key/create/key-name
    - /v1/key/generate/key-name
    - /v1/key/decrypt/key-name
    identities:
    - value-of-minio-certificate
...
```

#### Expected behavior
While trying to authenticate a client using a policy, we are getting "prohibited by policy" in audit logs after upgrading to v0.17.5 without any changes to our `kes.yml`. We've checked and it seems that the policy is correct according to the documentation, and also that the correct identity was being used according to the audit logs.

#### Additional context

1. What version of Go are you using (`go version`)?

`go version go1.15.14 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

`RHEL 7.9 amd64`

3. Anything else that is important?

We've downgraded from v0.17.5 to v0.17.2 and it's working again. We are wondering if [this](https://github.com/minio/kes/blob/a229d68fd98192ab4df32c296ab5febec172f5b8/internal/yml/server-config_v0.17.0.go#L25) should be `yaml:identities` instead of `yaml:identity` since the key name in the yaml should be `identities`

**Comment by harshavardhana** [comment] 2022-01-05 05:38
@staelen can you share whats your `kes -v` ?

**Comment by staelen** [comment] 2022-01-05 05:53
> @staelen can you share whats your `kes -v` ?

v0.17.5

**Comment by harshavardhana** [comment] 2022-01-05 06:44
Just tested everything seems to be working fine

```

address: 0.0.0.0:7373
root: disabled
tls:
  key: /tmp/kes/server.key
  cert: /tmp/kes/server.crt
policy:
  default-policy:
    paths:
    - /v1/key/create/my-minio-key
    - /v1/key/generate/my-minio-key
    - /v1/key/decrypt/my-minio-key
    identities:
    - ${MINIO_KES_IDENTITY}
cache:
  expiry:
    any: 5m0s
    unused: 20s
log:
  error: "on"
  audit: "off"
keys:
  vault:
    endpoint: http://vault.default.svc.cluster.local:8200
    prefix: my-minio
    approle:
      id: 9cc28db0-abee-0189-cfae-6750e3d0719e
      secret: 02c9646a-bf44-6910-09e6-1070e6180179
      retry: 15s
    tls: {}
    status:
      ping: 10s
```

**Comment by staelen** [comment] 2022-01-05 07:18
Hi @harshavardhana, noticed that you are using `paths` instead of `allow` in your policy, if I'm not mistaken, according to [here](https://github.com/minio/kes/blob/a229d68fd98192ab4df32c296ab5febec172f5b8/internal/yml/config.go#L158), you will be using `serverConfigV0140` which will not trigger the error from `serverConfigV0170`. Furthermore, from [here](https://github.com/minio/kes/blob/a229d68fd98192ab4df32c296ab5febec172f5b8/internal/yml/server-config_v0.14.0.go#L24), it's using `yaml:identities` which is correct. Do you mind checking again?

**Comment by aead** [comment] 2022-01-05 17:34
This seems to be a regression introduced by a229d68f.
See: [diff](https://github.com/minio/kes/commit/a229d68fd98192ab4df32c296ab5febec172f5b8#diff-5cf40da47d04b063455c5695e527445a1ac43902d8b35ffa21aaba1aa23126c0L268)

I will send a fix for this that will bring back the previous behaviour.

**Closed** 2022-01-06 18:01 UTC
Labels: bug
