### ISSUE TITLE
kubernetes probes using container curl command or not requiring mTLS for http

### ISSUE THREAD

**Issue by gutmensch** [minio/kes#353] opened 2023-04-19 07:06 UTC
#### What is the problem you want to solve?
I am running kes as a kubernetes container and would like to have proper liveness and readiness probes. For this purpose as far as I can see currently there are only two options:
1. Use a simple TCP check for kes on port 7373, which is likely unreliable/not comprehensive for testing functionality
2. Use a curl command inside the container like this, which uses a proper client identity for being able to check /v1/status
```
livenessProbe:
  exec:
    command: ['/bin/sh', '-ce', 'curl --connect-timeout 1 --cacert /opt/certs/ca.cert --cert /opt/certs/client.cert --key /opt/certs/client.key -s --fail -o /dev/null https://kes-server.local:7373/v1/status']
```
Kubernetes http probes do not support client certificate connections.

#### How do you want to solve it?
I'd like to ask for getting curl back into the original release image. It was there in the February image but was likely removed in commits to reduce the image size (I agree curl is a bit heavy, but has its value here IMO).

#### Additional context

1. Are there alternative solutions?
* running without probing
* using unreliable TCP checks only
* implement http probe endpoints in kes without mTLS requirement

4. Would your solution cause a major breaking API change?
No

5. Anything else that is important?

**Comment by harshavardhana** [comment] 2023-04-19 09:13
We would implement proper readiness, and liveness probes here that do not require any mTLS // cc @aead

**Comment by gutmensch** [comment] 2023-04-19 09:24
@harshavardhana Great input and idea, thanks. I listed this as another option, but I assume from the time perspective this will take quite some more time to implement compared to bringing back the state of having curl in the container like in February and before? From functionality point of view of the container image the removal of curl is a regression IMO that can be fixed easier until http probes are ready?

**Comment by aead** [comment] 2023-04-21 17:25
@gutmensch For a simple liveness check you can use the `/version` endpoint. It already does not require a mTLS connection - as long as you don't require client certificate chain verification (e.g. using the new recommended API keys).

@harshavardhana @gutmensch In general, we can add dedicated liveness and readyness endpoints. The an edge server (stateless) there is little value compared to `/version` and `/v1/status` but I can see the use case for the upcoming stateful KES server implementation.
Sounds reasonable to me.

@gutmensch I would like to avoid bringing back curl - unless there are reasonable use cases that cannot be solved by KES itself - since it:
 - it makes the container larger
 - adds components that aren't used by get reported by various security scanners whenever there is a CVE
 
I would like to keep the image as small as possible with as few dependencies as we can get away with.

**Comment by gutmensch** [comment] 2023-04-21 18:27
@aead Totally understand this, curl in the container was just a vehicle for me to get any useful liveness check. My config I shared here https://github.com/minio/kes/issues/352#issue-1673618904 and at the moment it seems nothing works to check without client certs? Or am I missing something?

```
$ kubectl exec -ti minio-0 -c kes -- sh                                                                                                                                                     
sh-4.4$ curl localhost:7373/version
Client sent an HTTP request to an HTTPS server.
sh-4.4$ curl -k https://localhost:7373/version
curl: (56) OpenSSL SSL_read: OpenSSL/1.1.1t: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0
```

It's not a crazy big deal for me, I had to rebuild the container now either way because of unprivileged security context and `setcap cap_ipc_lock+ep /kes` and in this step I also added a static curl back. It would just be good to have a generic check in the sense of "service is doing fine/KMS connection is working, etc" because ultimately my minio deployment depends on it now and a lot of services depend on this (e.g. nextcloud). Thanks either way for looking into it! Encryption works great now after the setup and the latest fixes for GCP.

**Comment by aead** [comment] 2023-04-21 18:57
@gutmensch Actually the `/version` approach does not work - my bad. The problem is that we rely on the TLS stack which aborts the handshake if no client certificate is sent.

The new liveness and readiness endpoints will fix this. In particular, for this you will need the new liveness and readiness API and this feature: https://github.com/minio/kes/blob/master/server-config.yaml#L54
Currently, you cannot make it work since there is no way to tell the KES TLS stack to allow clients send a request without having a TLS certificate.

I will close the issue once liveness and readiness have been merged. Then the upcoming release will expose these and you should be able to use K8S probes.

> Thanks either way for looking into it! Encryption works great now after the setup and the latest fixes for GCP.

👍

**Closed** 2023-04-24 10:09 UTC
